"""Add shares_outstanding and created_at to Stock table

Revision ID: 2fb25353f5bb
Revises: 7e8fcf2f3c01
Create Date: 2025-11-21 17:19:16.636319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb25353f5bb'
down_revision = '7e8fcf2f3c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shares_outstanding', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('shares_outstanding')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
