"""Add price column to Stock

Revision ID: 7e8fcf2f3c01
Revises: 
Create Date: 2025-11-21 17:15:20.226665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e8fcf2f3c01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_stock_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_user_id'))

    op.drop_table('portfolio')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_chat_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Stores chat conversation history'
    )

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('stock_symbol_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_stock_ticker'), ['ticker'], unique=True)
        batch_op.drop_table_comment(
        existing_comment='Stores stock information and current prices'
    )
        batch_op.drop_column('current_price')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('symbol')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_stock_id'))
        batch_op.drop_index(batch_op.f('ix_trade_timestamp'))
        batch_op.drop_index(batch_op.f('ix_trade_user_id'))
        batch_op.drop_constraint(batch_op.f('fk_trade_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trade_stock'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Records all buy and sell transactions'
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('user_username_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_table_comment(
        existing_comment='Stores user account information'
    )
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('10000.00'), autoincrement=False, nullable=True))
        batch_op.create_table_comment(
        'Stores user account information',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint(batch_op.f('user_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Records all buy and sell transactions',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trade_stock'), 'stock', ['stock_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_trade_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_trade_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_stock_id'), ['stock_id'], unique=False)

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.create_table_comment(
        'Stores stock information and current prices',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_stock_ticker'))
        batch_op.create_unique_constraint(batch_op.f('stock_symbol_key'), ['symbol'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('ticker',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('price')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Stores chat conversation history',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chat_user'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    op.create_table('portfolio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('average_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], name=op.f('fk_portfolio_stock'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_portfolio_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_pkey')),
    sa.UniqueConstraint('user_id', 'stock_id', name=op.f('uq_user_stock'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Tracks current holdings for each user'
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###
